pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoEventRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/event/EventMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/event/EventMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/event/EventMongoRepositoryImpl.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/EventMongo.java
src/test/java/io/gravitee/repository/mongodb/management/EventRepositoryTest.java
src/test/resources/data/event-tests/events.json

Unable to manually deploy API via Events.

Features/event : Manually deploy API to the Gateway

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoApiRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApiMongo.java

Associate a logo / a picture to an API

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PageMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PageSourceMongo.java

feat(page): Allow pages to be fetched from external resources

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoApiRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoApplicationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoUserRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/UserMongo.java

feat(security): Improve permission management

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoEventRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/event/EventMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/event/EventMongoRepositoryImpl.java

This closes gravitee-io/issues#113

feat(events): add search events method

---

src/main/java/io/gravitee/repository/mongodb/management/MongoEventRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/event/EventMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/event/EventMongoRepositoryImpl.java

feat(repository): Preserve a single method to search for events.

---

src/main/java/io/gravitee/repository/mongodb/management/MongoViewRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/ViewMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ViewMongo.java

This closes https://github.com/gravitee-io/issues/issues/112

Allows to group list of APIs by views

---

src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PageConfigurationMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PageMongo.java

feat(documentation): enable tryit mode on swagger

---

src/main/java/io/gravitee/repository/mongodb/management/MongoUserRepository.java

This closes https://github.com/gravitee-io/issues/issues/246

Allows to create an account from the application and update password

---

src/main/java/io/gravitee/repository/mongodb/management/MongoApiRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoApplicationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoGroupRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/group/GroupMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApiMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApplicationMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/GroupMongo.java

feat(group): manage group permissions

---

src/main/java/io/gravitee/repository/mongodb/management/MongoApiRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApiMongo.java

fix(definition): Add associated views into API entity

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PlanMongo.java

feat(plan): Add status to API plans

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoApplicationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepository.java
src/main/resources/scripts/create-index.js

feat(subscription): api publisher could add app subscription

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoTagRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/TagMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/TagMongo.java

This closes https://github.com/gravitee-io/issues/issues/318

Allows to CRUD sharding tags

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoViewRepository.java

chore(tests): add more tests

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoTenantRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/TenantMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/TenantMongo.java

feat(gateway): Multi-tenant support

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoApplicationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApplicationMongo.java

fix(application): archive an application

---

src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApiMongo.java

This closes https://github.com/gravitee-io/issues/issues/500

Apis with same name are filtered on hashed collections

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PageMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/page/PageMongoRepository.java

feat(pages): set a page as an api homepage

---

src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/page/PageMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/page/PageMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/page/PageMongoRepositoryImpl.java

feat(pages): add portal pages

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoMetadataRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/MetadataMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApiMetadataMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApiMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/MetadataMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/MetadataPkMongo.java

Add management of metadatas

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoApiRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApiMongo.java

feat(api): Associate labels to API

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoMembershipRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoRoleRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApplicationMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/RoleMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/RolePkMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/UserMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/role/RoleMongoRepository.java
src/main/resources/scripts/create-index.js

feat(roles): implementation of custom roles

---

src/main/java/io/gravitee/repository/mongodb/management/internal/model/SubscriptionMongo.java

Better management of closing plan : set a closed date on subscriptions and send a clearer email to all subscribers of the plan

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoApiRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoApplicationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoGroupRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoMembershipRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/ApiMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/group/GroupMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/membership/MembershipMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApiMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApplicationMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/GroupMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/MembershipMongo.java

feat(groups): move api/app groups to user groups

---

src/main/java/io/gravitee/repository/mongodb/management/MongoApiRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoApplicationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoEventRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoUserRepository.java

Application repository should not check invariant

---

src/main/java/io/gravitee/repository/mongodb/management/MongoApiKeyRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoApiRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoApplicationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoEventRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoGroupRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoMembershipRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoMetadataRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoPlanRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoRoleRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoSubscriptionRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoTagRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoTenantRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoUserRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoViewRepository.java

Make update mehods consistent

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PageMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PlanMongo.java

feat(groups): restrict pages and documentation to a set of groups

---

src/main/java/io/gravitee/repository/mongodb/management/MongoApiKeyRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/key/ApiKeyMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/key/ApiKeyMongoRepositoryImpl.java
src/main/resources/scripts/create-index.js

feat(apikey): New method for api-key refresh improvements

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoRatingAnswerRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoRatingRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/RatingAnswerMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/RatingMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/RatingAnswerMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/RatingMongo.java
src/main/resources/scripts/create-index.js

This closes gravitee-io/issues#840

Implementation of rating of APIs

---

src/main/java/io/gravitee/repository/mongodb/management/MongoAuditRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/audit/AuditMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/audit/AuditMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/audit/AuditMongoRepositoryImpl.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/AuditMongo.java
src/main/resources/scripts/create-index.js

feat(audit): first implementation

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoViewRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ViewMongo.java

feat(views): make views sortable, hidden and choose the default one

---

src/main/java/io/gravitee/repository/mongodb/management/internal/api/ApiMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/user/UserMongoRepository.java
src/main/resources/scripts/create-index.js

fix: improve perf to retrieve the list of apis and applications

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoApplicationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoSubscriptionRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApplicationMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PlanMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/SubscriptionMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/plan/SubscriptionMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/plan/SubscriptionMongoRepositoryImpl.java

feat(oauth2): Manage OAuth2 and JWT plan security type

---

src/main/resources/scripts/create-index.js

Closes gravitee-io/issues#1063

fix(mongodb): Add missing index

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoParameterRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/ParameterMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ParameterMongo.java

This closes gravitee-io/issues#932

feat: allows to configure top APIs displayed on portal

---

src/main/java/io/gravitee/repository/mongodb/management/MongoGenericNotificationConfigRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoPortalNotificationConfigRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoPortalNotificationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/GenericNotificationConfigMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PortalNotificationConfigMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PortalNotificationConfigPkMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PortalNotificationMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/notification/GenericNotificationConfigMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/notification/PortalNotificationConfigMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/notification/PortalNotificationMongoRepository.java
src/main/resources/scripts/create-index.js
src/test/java/io/gravitee/repository/mongodb/config/AbstractMongoRepositoryTest.java

feat(notifications): add user notifications

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoRatingRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/audit/AuditMongoRepositoryImpl.java

This closes gravitee-io/issues#344

feat: implementation of JDBC repository for version 1.14

---

src/main/java/io/gravitee/repository/mongodb/management/internal/model/SubscriptionMongo.java

feat(subscription): add a reason on accept and on request

---

src/main/java/io/gravitee/repository/mongodb/management/MongoMembershipRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoUserRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/membership/MembershipMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/user/UserMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/user/UserMongoRepositoryImpl.java

feat(user): add user management

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoGroupRepository.java

feat(group): Delegate the management of a group

---

pom.xml

Closes gravitee-io/issues#1208

chore: Upgrade Spring Data and MongoDB driver to 3.6.x

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ViewMongo.java

Closes gravitee-io/issues#1011

feat(view): add highlight API

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoUserRepository.java

fix(user): update user profile

---

src/main/java/io/gravitee/repository/mongodb/management/MongoApiRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/ApiMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/ApiMongoRepositoryImpl.java
src/main/java/io/gravitee/repository/mongodb/management/internal/audit/AuditMongoRepositoryImpl.java
src/main/java/io/gravitee/repository/mongodb/management/internal/event/EventMongoRepositoryImpl.java
src/main/java/io/gravitee/repository/mongodb/management/internal/plan/SubscriptionMongoRepositoryImpl.java
src/main/java/io/gravitee/repository/mongodb/management/internal/user/UserMongoRepositoryImpl.java

This closes gravitee-io/issues#561

feat: Allows to search and filter APIs

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/common/MongoFactory.java
src/main/java/io/gravitee/repository/mongodb/management/ManagementRepositoryConfiguration.java
src/main/java/io/gravitee/repository/mongodb/management/MongoApiKeyRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoApiRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoApplicationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoAuditRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoEventRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoGenericNotificationConfigRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoGroupRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoMembershipRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoMetadataRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoParameterRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoPlanRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoPortalNotificationConfigRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoPortalNotificationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoRatingAnswerRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoRatingRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoRoleRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoSubscriptionRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoTagRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoTenantRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoUserRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoViewRepository.java
src/main/java/io/gravitee/repository/mongodb/ratelimit/MongoRateLimitRepository.java
src/main/java/io/gravitee/repository/mongodb/ratelimit/RateLimitRepositoryConfiguration.java
src/test/java/io/gravitee/repository/mongodb/MongoTestRepositoryConfiguration.java
src/test/java/io/gravitee/repository/mongodb/MongoTestRepositoryInitializer.java

This closes gravitee-io/issues#1386

chore: Upgrade Spring Data Mongodb dependencies

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoDictionaryRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/dictionary/DictionaryMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/DictionaryMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/DictionaryProviderMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/DictionaryTriggerMongo.java

Closes gravitee-io/issues#1400

feat(dictionary): Add global dictionary

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoApiHeaderRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/ApiHeaderMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApiHeaderMongo.java

feat(api-portal-header): edit headers

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoGenericNotificationConfigRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/GenericNotificationConfigMongo.java

feat(proxy): add global proxy

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoMediaRepository.java

feat(portal): Allows to persist images to use it on documentation pages

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/common/AbstractRepositoryConfiguration.java
src/main/java/io/gravitee/repository/mongodb/management/MongoIdentityProviderRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoUserRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/identityprovider/IdentityProviderMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/IdentityProviderMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/UserMongo.java
src/main/java/io/gravitee/repository/mongodb/management/mapper/GraviteeDozerMapper.java
src/main/java/io/gravitee/repository/mongodb/management/mapper/GraviteeMapper.java
src/main/java/io/gravitee/repository/mongodb/management/mapper/RepositoryDozerClassLoader.java
src/main/resources/dozer.xml
src/test/java/io/gravitee/repository/mongodb/MongoTestRepositoryConfiguration.java

Closes gravitee-io/issues#1595

feat(user): Refactor user management and identity provider

---

src/main/java/io/gravitee/repository/mongodb/management/MongoAlertRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/AlertMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/AlertMongo.java

This closes gravitee-io/issues#63

feat: allows to send an alert when the HC status changes

---

src/main/java/io/gravitee/repository/mongodb/ratelimit/MongoRateLimitRepository.java

Closes gravitee-io/issues#1748

fix(ratelimit): Handle empty constructor after latest Spring upgrade

---

pom.xml

Closes gravitee-io/issues#1658

feat(audit): Add event for API rollback

---

pom.xml

Closes gravitee-io/issues#1762

feat(plan): A plan can be depreciate to close subscriptions

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoAlertRepository.java

This closes gravitee-io/issues#1801

fix: Alert is not correctly mapped on some cases

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApiKeyMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/SubscriptionMongo.java

Closes gravitee-io/issues#1753

feat(souscription): A subscription can be paused and resumed

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoEntrypointRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/EntrypointMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/EntrypointMongo.java

This closes gravitee-io/issues#1706

feat: display entrypoints by API sharding tags

---

src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/page/PageMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/page/PageMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/page/PageMongoRepositoryImpl.java

feat(pages): redesign management + multi subfolder

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PageMongo.java

This closes gravitee-io/issues#1825

fix: Add a link to the git repository defined on a documentation page

---

src/main/java/io/gravitee/repository/mongodb/management/internal/model/ViewMongo.java

closes gravitee-io/issues#1821

feat(view): add picture to a portal view

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PlanMongo.java

fix(plan) do not redeploy api on every plan modification

---

src/main/java/io/gravitee/repository/mongodb/management/MongoAlertRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoInvitationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/InvitationMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/GroupMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/InvitationMongo.java

This closes gravitee-io/issues#1818

feat: Invite a user in a group

---

src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java

feat(tree): fetch pages recursively

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/internal/user/UserMongoRepositoryImpl.java

This closes gravitee-io/issues#1988

fix: Search users is not well ordered

---

pom.xml
src/test/java/io/gravitee/repository/mongodb/MongoTestFactory.java
src/test/java/io/gravitee/repository/mongodb/MongoTestRepositoryConfiguration.java
src/test/resources/logback-test.xml

chore: Java 11 support

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoUserRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/UserMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/user/UserMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/user/UserMongoRepositoryImpl.java

feat(user): archive users

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/internal/user/UserMongoRepository.java

fix(user): sourceId search must be case insensitive

---

src/main/java/io/gravitee/repository/mongodb/management/MongoApplicationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoClientRegistrationProviderRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/application/ClientRegistrationProviderMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApplicationMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ClientRegistrationProviderMongo.java
src/test/resources/logback-test.xml

Closes gravitee-io/issues#1580

feat(dcr): Add Dynamic Client Registration support

---

src/main/java/io/gravitee/repository/mongodb/management/MongoTagRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/TagMongo.java

This closes gravitee-io/issues#1995

feat: Allows to define permission to publish on a sharding tag

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoClientRegistrationProviderRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ClientRegistrationProviderMongo.java

Closes gravitee-io/issues#2207

feat(dcr): Support multiple initial access token providers

---

src/main/java/io/gravitee/repository/mongodb/management/MongoIdentityProviderRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/IdentityProviderMongo.java

refactoring from 1.20.16 due to new idp management
fix gravitee-io/issues#2124

feat(idp): oauth idp could authorize users without email

---

src/main/java/io/gravitee/repository/mongodb/management/MongoApiRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoWorkflowRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/ApiMongoRepositoryImpl.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/WorkflowMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApiMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/WorkflowMongo.java

This closes gravitee-io/issues#1996

feat: lifecycle API and review workflow

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PlanMongo.java

Closes gravitee-io/issues#2219

feat(plan): Manage plan deployment using sharding tags

---

src/main/java/io/gravitee/repository/mongodb/management/MongoClientRegistrationProviderRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ClientRegistrationProviderMongo.java

Closes gravitee-io/issues#2350

feat(application): Add renew client_secret support

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoUserRepository.java

fix(user): escape special characters on login

---

src/main/java/io/gravitee/repository/mongodb/management/MongoApplicationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApplicationMongo.java

Closes gravitee-io/issues#2288

feat(env): add 'picture' management for Application

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/common/MongoFactory.java
src/main/java/io/gravitee/repository/mongodb/ratelimit/MongoRateLimitRepository.java
src/main/java/io/gravitee/repository/mongodb/ratelimit/RateLimitRepositoryConfiguration.java

Closes gravitee-io/issues#2570

Rx ratelimit

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoGenericNotificationConfigRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoPortalNotificationConfigRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/notification/GenericNotificationConfigMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/notification/PortalNotificationConfigMongoRepository.java

fix(user): remove user notif on delete user

---

src/main/java/io/gravitee/repository/mongodb/management/MongoPortalNotificationRepository.java

Closes gravitee-io/issues#2699

feat(v3): add & implement findById

---

src/main/java/io/gravitee/repository/mongodb/management/MongoDashboardRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/DashboardMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/DashboardMongo.java

Closes gravitee-io/issues#2595

feat: Dynamic global dashboards of analytics

---

src/main/java/io/gravitee/repository/mongodb/management/MongoAlertRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/AlertMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/AlertTriggerMongo.java

Closes gravitee-io/issues#2777

feat(alert): Alerting integration

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoMembershipRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoPortalNotificationConfigRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/membership/MembershipMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/notification/PortalNotificationConfigMongoRepository.java

fix(api): delete memberships and notifications on delete

---

src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java

Closes gravitee-io/issues#3071

feat(portal): replace PageType enum with string

---

src/main/java/io/gravitee/repository/mongodb/common/MongoFactory.java
src/main/java/io/gravitee/repository/mongodb/management/ManagementRepositoryConfiguration.java

Closes gravitee-io/issues#3169

fix(mongo): Mongo singleton instance must be managed by the bean factory

---

src/main/java/io/gravitee/repository/mongodb/management/MongoEnvironmentRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoOrganizationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoRoleRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoUserRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoViewRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/OrganizationMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/RoleMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/RolePkMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/UserMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ViewMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ViewPkMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/organization/OrganizationMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/role/RoleMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/user/UserMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/user/UserMongoRepositoryImpl.java
src/main/resources/dozer.xml

Closes gravitee-io/issues#3182

feat(multi-env): add organization feature

---

pom.xml

Closes gravitee-io/issues#3235

chore: Upgrade MongoDB driver

---

src/main/java/io/gravitee/repository/mongodb/management/MongoThemeRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/ThemeMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ThemeMongo.java

feat: add theme repository

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoAlertEventRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/AlertEventMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/AlertEventMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/AlertEventMongoRepositoryImpl.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/AlertEventMongo.java
src/main/resources/scripts/create-index.js

Closes gravitee-io/issues#3185

feat(alert): Add alert history

---

src/main/java/io/gravitee/repository/mongodb/management/MongoUserRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/UserMongo.java

feat: Allow users to subscribe to newsletters

---

src/main/java/io/gravitee/repository/mongodb/management/internal/api/ViewMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ViewMongo.java

Closes gravitee-io/issues#3767

feat(management): remove 'default' field from views

---

src/main/java/io/gravitee/repository/mongodb/ratelimit/MongoRateLimitRepository.java

chore: Merge 1.30.11

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoAlertRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/AlertEventRuleMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/AlertTriggerMongo.java

Closes gravitee-io/issues#3970

feat(alert): Support for alert templates

---

src/main/java/io/gravitee/repository/mongodb/management/MongoCommandRepository.java

fix: Better handling of indexation of searchable data

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoApplicationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApiMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApplicationMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/CategoryMongo.java

feat: Allows to define a background on the APIs/Apps/Categories headers

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoUserRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/UserMongo.java

feat: Allows user to subscribe to the newsletter after login

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoApplicationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApiMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApplicationMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/GroupMongo.java

Closes gravitee-io/issues#4134

feat(management): add a "disableEmailNotification" option in groups, APIs and applications

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoPageRevisionRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PageRevisionMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PageRevisionPkMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/page/revision/PageRevisionMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/page/revision/PageRevisionMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/page/revision/PageRevisionMongoRepositoryImpl.java
src/main/resources/dozer.xml

feat(management-api/reporter): #146 addition of page revision

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoIdentityProviderRepository.java

fix(management): change the findAll to compute groupMappings

---

src/main/java/io/gravitee/repository/mongodb/management/MongoCategoryRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/CategoryMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/CategoryMongo.java

Closes gravitee-io/issues#4067

feat(management): associate a page to a category

---

src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PageMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/page/PageMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/page/PageMongoRepositoryImpl.java
src/main/resources/scripts/create-index.js

Addition of findAll method on PageRepository
fix gravitee-io/issues#3196

feat(management): auto fetch pages based on user configuration

---

src/main/java/io/gravitee/repository/mongodb/management/MongoMediaRepository.java

fix gravitee-io/issues#4149
fix gravitee-io/issues#3156

fix(management): resolve API import/export

---

src/main/resources/scripts/create-index.js

fix(index): do not create indexes on unknown attributes

---

src/main/java/io/gravitee/repository/mongodb/management/MongoCommandRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoCustomUserFieldsRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/CustomUserFieldMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/CustomUserFieldPkMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/user/CustomUserFieldsMongoRepository.java
src/main/resources/dozer.xml
src/main/resources/scripts/create-index.js

feat(mgnt/portal): Addition of CustomUserFieldsRepository

---

src/main/java/io/gravitee/repository/mongodb/management/MongoMediaRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PageMediaMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PageMongo.java

Closes gravitee-io/issues#4066

feat(management): add assets to pages

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoIdentityProviderRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoUserRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/identityprovider/IdentityProviderMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/IdentityProviderMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/UserMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/user/UserMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/user/UserMongoRepositoryImpl.java

Closes gravitee-io/issues#3973

feat(repository): replace refId & refType with organizationId

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoIdentityProviderActivationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/identityprovideractivation/IdentityProviderActivationMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/IdentityProviderActivationMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/IdentityProviderActivationPkMongo.java

Closes gravitee-io/issues#3963

feat(repository): idp links with an env or an org are now stored

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoNotificationTemplateRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/NotificationTemplateMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/notification/NotificationTemplateMongoRepository.java

+ upgrade gravitee dependancies
Closes gravitee-io/issues#4297

feat(notification): manage notif template in database

---

src/main/java/io/gravitee/repository/mongodb/management/MongoTicketRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/TicketMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/ticket/TicketMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/ticket/TicketMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/ticket/TicketMongoRepositoryImpl.java
src/main/java/io/gravitee/repository/mongodb/utils/FieldUtils.java
src/test/java/io/gravitee/repository/mongodb/utils/FieldUtilsTest.java

feat: support tickets history

---

pom.xml

fix: Simple user without groups can see all the applications

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoParameterRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/ParameterMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ParameterMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ParameterPkMongo.java

Closes gravitee-io/issues#4642

feat(repository): manage Org & Env in parameters

---

pom.xml

Fixes https://github.com/gravitee-io/issues/issues/4679

fix: backport 4678

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoUserRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/user/UserMongoRepository.java

feat(repository/user): addition of findByEmail

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoEnvironmentRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoOrganizationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/environment/EnvironmentMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/EnvironmentMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/OrganizationMongo.java

Closes gravitee-io/issues#4287

feat(cockpit): handle organization and environment commands

---

src/main/java/io/gravitee/repository/mongodb/management/MongoInstallationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/installation/InstallationMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/InstallationMongo.java

Closes gravitee-io/issues#4766

feat(cockpit): manage cockpit installation registration

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoDictionaryRepository.java

Closes gravitee-io/issues#5072

fix(dictionary): Add new tests for dictionary, property's keys containing a dot (.)

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/internal/model/GroupMongo.java

Closes gravitee-io/issues#5133

feat(management): Manage API PO in a group

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/common/AbstractRepositoryConfiguration.java
src/main/java/io/gravitee/repository/mongodb/ratelimit/MongoRateLimitRepository.java
src/main/resources/scripts/create-index.js
src/test/resources/graviteeTest.yml

Fixes https://github.com/gravitee-io/issues/issues/4715

feat: allows to define a prefix for collections / tables

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoOrganizationRepository.java

fix(repository): fully update an organization

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PageMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/page/PageMongoRepositoryImpl.java
src/main/java/io/gravitee/repository/mongodb/management/mapper/NullToDefaultValueConverter.java
src/main/resources/dozer.xml

Fixes https://github.com/gravitee-io/issues/issues/4893

feat: setting to make portal pages non-visible for anonymous user

---

src/main/java/io/gravitee/repository/mongodb/management/MongoThemeRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ThemeMongo.java

feat(portal): allows to change favicon

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoMembershipRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoOrganizationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/membership/MembershipMongoRepository.java

Closes gravitee-io/issues#5360

Merge 3.6.2

---

src/main/java/io/gravitee/repository/mongodb/management/MongoNodeMonitoringRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/MonitoringMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/node/NodeMonitoringMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/node/NodeMonitoringMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/node/NodeMonitoringMongoRepositoryImpl.java

Closes gravitee-io/issues#5104

feat(cockpit): Propagate monitoring data to cockpit

---

src/main/java/io/gravitee/repository/mongodb/management/MongoPageRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/AccessControlMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PageMongo.java

feat: add ACL on custom link

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/MongoApplicationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepository.java

Fixes https://github.com/gravitee-io/issues/issues/4453

feat: allow to restore an archived application

---

src/main/java/io/gravitee/repository/mongodb/management/MongoEntrypointRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoGroupRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoTagRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoTenantRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/EntrypointMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/TagMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/TenantMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/EntrypointMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/TagMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/TenantMongo.java

feat: associate sharding tags and tenants to organization

---

src/main/java/io/gravitee/repository/mongodb/management/MongoDictionaryRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoEnvironmentRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoEventRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoOrganizationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/ApiMongoRepositoryImpl.java
src/main/java/io/gravitee/repository/mongodb/management/internal/dictionary/DictionaryMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/environment/EnvironmentMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/event/EventMongoRepositoryImpl.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/EventMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/organization/OrganizationMongoRepository.java

Fixes https://github.com/gravitee-io/issues/issues/5357

feat: allow to associate a gateway to environments

---

pom.xml
src/main/java/io/gravitee/repository/mongodb/management/internal/api/ApiMongoRepositoryImpl.java

Closes gravitee-io/issues#5298

feat(management): allow to filter by context-path

---

src/main/java/io/gravitee/repository/mongodb/management/MongoApplicationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepositoryImpl.java

fix: search only user authorized applications by name

---

src/main/java/io/gravitee/repository/mongodb/management/MongoAlertRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/api/AlertMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/application/ApplicationMongoRepositoryImpl.java

* search applications in many environments
* search alertTrigger for many references
Closes gravitee-io/issues#5341

feat(management): allow to define consumer alerts

---

src/main/java/io/gravitee/repository/mongodb/management/internal/plan/SubscriptionMongoRepositoryImpl.java

**Issue**
https://github.com/gravitee-io/issues/issues/3887
**Description**
- Add fields to handle `endingAt` in SubscriptionCriteria

Handle criteria on endingAt field of Subscription

---

src/main/java/io/gravitee/repository/mongodb/management/MongoFlowRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoOrganizationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/flow/FlowMongoRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/FlowMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/OrganizationMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/TagMongo.java

feat(management): platform policies

---

src/main/java/io/gravitee/repository/mongodb/management/internal/key/ApiKeyMongoRepositoryImpl.java

**Issue**
https://github.com/gravitee-io/issues/issues/3887

feat: handle fields to filter api key by expiration date

---

README.md
pom.xml
src/main/java/io/gravitee/repository/mongodb/management/internal/model/ApiKeyMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/SubscriptionMongo.java

**Issue**
https://github.com/gravitee-io/issues/issues/3887

feat: add field to store info about the last pre expiration notif sent

---

pom.xml

Closes gravitee-io/issues#5670

chore: add spring reactor dependency

---

src/main/java/io/gravitee/repository/mongodb/management/MongoPromotionRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PromotionMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/promotion/PromotionMongoRepository.java

**Issue**
https://github.com/gravitee-io/issues/issues/5526
**Description**
Implement `PromotionRepository`.

Implement PromotionRepository

---

src/main/java/io/gravitee/repository/mongodb/management/MongoEnvironmentRepository.java
src/main/java/io/gravitee/repository/mongodb/management/MongoOrganizationRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/EnvironmentMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/OrganizationMongo.java

**Issue**
https://github.com/gravitee-io/issues/issues/5781
**Description**
The goal of introducing these cockpit ids is to ease the management of DEFAULT env/org on APIM side when working with BridgeCommand

Introduce cockpit id

---

src/main/java/io/gravitee/repository/mongodb/management/MongoPromotionRepository.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PromotionAuthorMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/model/PromotionMongo.java
src/main/java/io/gravitee/repository/mongodb/management/internal/promotion/PromotionMongoRepositoryCustom.java
src/main/java/io/gravitee/repository/mongodb/management/internal/promotion/PromotionMongoRepositoryImpl.java

**Issue**
https://github.com/gravitee-io/issues/issues/5527
**Description**
- Implement search method in `PromotionRepository`
- Update Promotion-related classes to handle source and target env names, author and apiId fields

Handle search method in PromotionRepository and new fields in Promotion
